graphhopper:
 
  datareader.file: your_local_file_path.osm.pbf
  graph.location: germany-gh
  profiles:
    - name: bike
      vehicle: bike
      weighting: custom
      custom_model_file: empty
    - name: foot
      vehicle: foot
      weighting: custom
      custom_model_file: empty
    - name: car
      vehicle: car
      weighting: custom
      custom_model_file: empty
      turn_costs: true
      u_turn_costs: 60
 
server:
  application_connectors:
  - type: http
    port: 8989
    bind_host: localhost # for security reasons bind to localhost
  request_log:
      appenders: []
